"""ai_spend_tracker.py - drop-in usage + cost logger (generated by the AI Model Savings Scanner).

Call record_usage(...) right after each model call. It logs one JSON line per call to
AI_SPEND_LOG (default ./ai_spend_log.jsonl) with token counts, the actual cost, and the
counterfactual cost on the baseline (old) model so you can measure real savings.

Privacy: raw prompt/output text is NOT stored by default (only length + a short hash).
Set AI_SPEND_STORE_TEXT=1 to store truncated text.

Remote dashboard: set AI_SPEND_API_URL=https://<your-scanner-site> to also POST each
record to the hosted scanner's /api/track endpoint, feeding its live /dashboard.
"""

import json
import os
import threading
import time
import datetime
import hashlib
import urllib.request

LOG_PATH = os.environ.get("AI_SPEND_LOG", "ai_spend_log.jsonl")
STORE_TEXT = os.environ.get("AI_SPEND_STORE_TEXT", "") in ("1", "true", "True", "yes")
API_URL = os.environ.get("AI_SPEND_API_URL", "http://aiapitest-production.up.railway.app").rstrip("/")
CLIENT_KEY = os.environ.get("AI_SPEND_CLIENT_KEY", "ck_efa410ee088b3a492eb85289710c3252")
DEFAULT_LABEL = os.environ.get("AI_SPEND_LABEL", "Chanman02222002/thisisshitty-pr-test")

# $ per 1M tokens. Edit these to match your live contract pricing.
PRICES = {
    "gpt-3.5-turbo": {
        "input": 0.5,
        "output": 1.5
    },
    "gpt-3.5-turbo-0125": {
        "input": 0.5,
        "output": 1.5
    },
    "gpt-3.5-turbo-1106": {
        "input": 1.0,
        "output": 2.0
    },
    "gpt-3.5-turbo-16k": {
        "input": 3.0,
        "output": 4.0
    },
    "gpt-4o": {
        "input": 2.5,
        "output": 10.0
    },
    "gpt-4-turbo": {
        "input": 10.0,
        "output": 30.0
    },
    "gpt-4": {
        "input": 30.0,
        "output": 60.0
    },
    "gpt-4o-mini": {
        "input": 0.15,
        "output": 0.6
    },
    "claude-3-opus": {
        "input": 15.0,
        "output": 75.0
    },
    "claude-3.5-sonnet": {
        "input": 3.0,
        "output": 15.0
    },
    "claude-3-haiku": {
        "input": 0.25,
        "output": 1.25
    },
    "gemini-1.5-pro": {
        "input": 3.5,
        "output": 10.5
    },
    "gemini-1.5-flash": {
        "input": 0.075,
        "output": 0.3
    },
    "mistral-large": {
        "input": 2.0,
        "output": 6.0
    },
    "mistral-small": {
        "input": 0.2,
        "output": 0.6
    }
}


def _price(model):
    return PRICES.get((model or "").strip().lower())


def _cost(model, prompt_tokens, completion_tokens):
    p = _price(model)
    if not p:
        return None
    return (prompt_tokens / 1_000_000.0) * p["input"] + (completion_tokens / 1_000_000.0) * p["output"]


def _extract(response):
    """Pull (model, prompt_tokens, completion_tokens) from an OpenAI / Anthropic / Google response."""
    model = getattr(response, "model", None)
    usage = getattr(response, "usage", None)
    pt = ct = None
    if usage is not None:
        pt = getattr(usage, "prompt_tokens", None)
        if pt is None:
            pt = getattr(usage, "input_tokens", None)
        if pt is None:
            pt = getattr(usage, "prompt_token_count", None)
        ct = getattr(usage, "completion_tokens", None)
        if ct is None:
            ct = getattr(usage, "output_tokens", None)
        if ct is None:
            ct = getattr(usage, "candidates_token_count", None)
    return model, int(pt or 0), int(ct or 0)


def record_usage(call_id, response=None, *, model=None, baseline_model=None,
                 prompt_tokens=None, completion_tokens=None,
                 input_text=None, output_text=None, label=None):
    """Log one call. Pass the raw response (preferred) or explicit token counts."""
    if response is not None:
        m, pt, ct = _extract(response)
        model = model or m
        if prompt_tokens is None:
            prompt_tokens = pt
        if completion_tokens is None:
            completion_tokens = ct
    prompt_tokens = int(prompt_tokens or 0)
    completion_tokens = int(completion_tokens or 0)
    total = prompt_tokens + completion_tokens
    actual = _cost(model, prompt_tokens, completion_tokens)
    baseline = _cost(baseline_model or model, prompt_tokens, completion_tokens)
    rec = {
        "ts": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "call_id": call_id,
        "client_key": (CLIENT_KEY or None),
        "label": (label or (DEFAULT_LABEL or None)),
        "model": model,
        "baseline_model": baseline_model or model,
        "prompt_tokens": prompt_tokens,
        "completion_tokens": completion_tokens,
        "total_tokens": total,
        "actual_cost": (round(actual, 8) if actual is not None else None),
        "baseline_cost": (round(baseline, 8) if baseline is not None else None),
        "savings": (None if (actual is None or baseline is None) else round(baseline - actual, 8)),
        "input_chars": (len(input_text) if input_text else None),
        "output_chars": (len(output_text) if output_text else None),
        "input_sha1": (hashlib.sha1(input_text.encode("utf-8")).hexdigest()[:12] if input_text else None),
    }
    if STORE_TEXT:
        rec["input_text"] = (input_text or "")[:2000]
        rec["output_text"] = (output_text or "")[:2000]
    try:
        with open(LOG_PATH, "a", encoding="utf-8") as f:
            f.write(json.dumps(rec) + "\n")
    except Exception:
        pass
    if API_URL:
        def _post():
            try:
                req = urllib.request.Request(API_URL + "/api/track",
                                             data=json.dumps(rec).encode("utf-8"),
                                             headers={"Content-Type": "application/json"})
                urllib.request.urlopen(req, timeout=4)
            except Exception:
                pass
        threading.Thread(target=_post, daemon=True).start()
    return rec


class track:
    """Context manager alternative: with track(call_id, baseline_model=...) as t: ...; t.set(resp)."""
    def __init__(self, call_id, baseline_model=None, model=None, input_text=None, label=None):
        self.call_id = call_id
        self.baseline_model = baseline_model
        self.model = model
        self.input_text = input_text
        self.label = label
        self.response = None

    def __enter__(self):
        self._t0 = time.time()
        return self

    def set(self, response):
        self.response = response
        return response

    def __exit__(self, *exc):
        record_usage(self.call_id, self.response, model=self.model,
                     baseline_model=self.baseline_model, input_text=self.input_text, label=self.label)
        return False
